### ISSUE TITLE
Additional material for Intro to Py Wk2 - df.info(), df.tail(), and df.head OR df.tail(n)

### ISSUE THREAD

**Issue by Chilliwack** [fredhutchio/python_intro#11]
Additional material for Intro to Py Wk2...maybe???

- [df.info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)
- [df.tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html)
- [df.head OR df.tail(n)](http://www.datasciencemadesimple.com/head-and-tail-in-python-pandas/)

**Comment by k8hertweck** [comment]
Sounds good!

**Comment by Chilliwack** [comment]
Made and submitted this change here https://github.com/fredhutchio/python_intro/pull/16. Please let me know if this isnt where you want it and ill move it
