### ISSUE TITLE
Kewl way(s) to create a ref of cols and index in a df; fit into course material some how

### ISSUE THREAD

**Issue by Chilliwack** [fredhutchio/python_intro#12]
Sometimes when reading in a long df it gets tricky to remember each column name and where it is by index. Here is a simple list comprehension to build up a reference list of all columns and their index.

`col_mapping = [f"{c[0]}:{c[1]}" for c in enumerate(df.columns)]`

In some cases if you might want to rename a bunch of columns, you can use a dictionary comprehension to create a dictionary view of the data:

`col_mapping_dict = {c[0]:c[1] for c in enumerate(df.columns)}`

**Comment by k8hertweck** [comment]
This sounds like a cool thing, and I like how it integrates for loops and dictionary usage from week 1. I'm concerned about how much time it would take to include this in an exercise.

**Comment by Chilliwack** [comment]
Proposed an update for this here https://github.com/fredhutchio/python_intro/pull/17 but trimmed it a bit bc it was repetitive.
